action_points_per_turn = 24
create_character_messages = ["You wake up on a beach", "You feel thirsty ..."]
fresh_water_resource_id = "FRESH_WATER"
liquid_material_id = "LIQUID"
fill_with_material_ids = ["LIQUID", "SANDY"]
default_weight_capacity = 20000.0
default_clutter_capacity = 5.0

[materials]
  [materials.LIQUID]
    name = "Liquide"

  [materials.SANDY]
    name = "Sableu"

  [materials.LITTLE_OBJECT]
    name = "Petit objets"

  [materials.SMALL_PIECE]
    name = "Petit morceau"

  [materials.MIDDLE_PIECE]
    name = "Moyen morceau"

  [materials.GAS]
    name = "Gazeu"

[character_effects]
  [character_effects.THIRSTY_SATISFIED]
    attributes_to_false = ["dehydrated", "feel_thirsty"]

  [character_effects.DRUNK]
    factors = [{"attribute"="bravery", "factor"=1.1}]

[resources]
  [resources.FRESH_WATER]
    name = "Eau potable"
    weight=1000.0
    material="LIQUID"
    unit = "L"
    clutter = 1.0
    actions = ["DROP_RESOURCE", "MIX_RESOURCES"]

  [resources.SALTED_WATER]
    name = "Eau salée"
    weight=1000.0
    material="LIQUID"
    unit = "L"
    clutter = 1.0
    actions = ["DROP_RESOURCE", "MIX_RESOURCES"]

  [resources.RED_WINE]
    name = "Vin rouge"
    weight=1000.0
    material="LIQUID"
    unit = "L"
    clutter = 1.0
    actions = ["DROP_RESOURCE", "MIX_RESOURCES"]

  [resources.WHITE_WINE]
    name = "Vin blanc"
    weight=1000.0
    material="LIQUID"
    unit = "L"
    clutter = 1.0
    actions = ["DROP_RESOURCE", "MIX_RESOURCES"]

  [resources.BEACH_SAND]
    name = "Sable de plage"
    weight=1600.0
    material="SANDY"
    unit = "L"
    clutter = 1.0
    actions = ["DROP_RESOURCE", "MIX_RESOURCES"]

  [resources.PEBBLES]
    name = "Galets"
    weight=2000.0
    material="LITTLE_OBJECT"
    unit = "L"
    clutter = 1.0
    actions = ["DROP_RESOURCE", "MIX_RESOURCES"]

  [resources.AIR]
    name = "Air"
    weight=0.0
    material="GAS"
    unit = "L"
    clutter = 1.0
    actions = ["DROP_RESOURCE", "MIX_RESOURCES"]

  [resources.DIRT]
    name = "Terre"
    weight=1500.0
    material="SANDY"
    unit = "L"
    clutter = 1.0
    actions = ["DROP_RESOURCE", "MIX_RESOURCES"]

  [resources.WET_DIRT]
    name = "Terre mouillé"
    weight=2000.0
    material="SANDY"
    unit = "L"
    clutter = 1.0
    actions = ["DROP_RESOURCE", "MIX_RESOURCES"]

  [resources.BRANCHES]
    name = "Petit bois"
    weight=20000.0
    material="MIDDLE_PIECE"
    unit = "M3"
    clutter = 1000.0
    actions = ["DROP_RESOURCE", "MIX_RESOURCES"]

[resource_mix]
  [resource_mix.WET_DIRT_WITH_FRESH_WATER]
    require = [{resource_id="FRESH_WATER", coeff=0.75}, {resource_id="DIRT", coeff=0.25}]
    produce = "WET_DIRT"
    # TODO BS 2019-09-06: currently, all are L, but if not ? how to do ?
    cost = 0.05
  [resource_mix.WET_DIRT_WITH_SALTED_WATER]
    require = [{resource_id="SALTED_WATER", coeff=0.75}, {resource_id="DIRT", coeff=0.25}]
    produce = "WET_DIRT"
    # TODO BS 2019-09-06: currently, all are L, but if not ? how to do ?
    cost = 0.05

[extractions]
  [extractions.FRESH_WATER]
    tile="FRESH_WATER"
    resources=[{resource_id="FRESH_WATER", cost_per_unit=0.1, default_quantity=1.0}]
    
  [extractions.SEA_WATER]
    tile="SEA_WATER"
    resources=[{resource_id="SALTED_WATER", cost_per_unit=0.1, default_quantity=1.0}]
    
  [extractions.SAND]
    tile="SAND"
    resources=[{resource_id="BEACH_SAND", cost_per_unit=0.1, default_quantity=1.0}]

  [extractions.DEAD_TREE]
    tile="DEAD_TREE"
    resources=[{resource_id="BRANCHES", cost_per_unit=2.0, default_quantity=0.04}]

  [extractions.DIRT]
    tile="DIRT"
    resources=[{resource_id="DIRT", cost_per_unit=0.1, default_quantity=1.0}]

  [extractions.HIGH_GRASS]
    tile="HIGH_GRASS"
    resources=[{resource_id="DIRT", cost_per_unit=0.15, default_quantity=1.0}]

  [extractions.SHORT_GRASS]
    tile="SHORT_GRASS"
    resources=[{resource_id="DIRT", cost_per_unit=0.15, default_quantity=1.0}]

[ACTIONS]
  [ACTIONS.DRINK_FRESH_WATER]
    actions = ["DRINK_RESOURCE", "DRINK_STUFF"]
    accept_resources = ["FRESH_WATER"]
    character_effects = ["THIRSTY_SATISFIED"]
    cost = 0.0

  [ACTIONS.DRINK_WINE]
    actions = ["DRINK_RESOURCE", "DRINK_STUFF"]
    accept_resources = ["RED_WINE", "WHITE_WINE"]
    character_effects = ["DRUNK"]
    cost = 0.0

  [ACTIONS.FILL_STUFF]
    actions = ["FILL_STUFF"]
    cost = 0.0

  [ACTIONS.EMPTY_STUFF]
    actions = ["EMPTY_STUFF"]
    cost = 0.0

  [ACTIONS.USE_AS_BAG]
    actions = ["USE_AS_BAG"]
    cost = 0.0

  [ACTIONS.NOT_USE_AS_BAG]
    actions = ["NOT_USE_AS_BAG"]
    cost = 0.0

  [ACTIONS.COLLECT_RESOURCE]
    actions = ["COLLECT_RESOURCE"]
    cost = 0.0

  [ACTIONS.DROP_RESOURCE]
    actions = ["DROP_RESOURCE", "MIX_RESOURCES"]
    cost = 0.0

  [ACTIONS.DROP_STUFF]
    actions = ["DROP_STUFF"]
    cost = 0.0

#  [ACTIONS.CRAFT_CAMPFIRE]
#    actions = ["CRAFT_FROM_RESOURCES"]
#    required_resources = [{resource="WOOD", required=5.0}, {resource="TWIGS", required=20.0}]
#    craft_on_zone = "CAMP_FIRE"
#    cost = 2.0
