[CORPSE]  # system required
  name = "Corps"
  weight = 80000.0
  clutter = 15.0
  actions = ["DROP_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  material_type = "SOLID"

[LITTLE_SKIN_CANTEEN]
  name = "Petite gourde de peau"
  filled_at = 0.0
  filled_unity = "L"
  filled_capacity = 1.0
  weight = 0.1
  clutter = 1.0
  actions = ["DROP_STUFF","FILL_STUFF","DRINK_STUFF","EMPTY_STUFF"]
  material_type = "OBJECT"
  classes = ["BOTTLE"]
[BASKETRY_BAG]
  name = "Sac végétal"
  weight = 1000.0
  clutter = 2.0
  clutter_capacity = 4.0
  actions = ["DROP_STUFF","USE_AS_BAG","NOT_USE_AS_BAG", "CONTINUE_STUFF_CONSTRUCTION"]
  material_type = "OBJECT"
  is_bag = true
  classes = ["BAG", "LITTLE_BAG", "BASKETRY_BAG"]
[SKIN_BAG]
  name = "Sac de peaux"
  weight = 2000.0
  clutter = 2.0
  clutter_capacity = 5.0
  actions = ["DROP_STUFF","USE_AS_BAG","NOT_USE_AS_BAG", "CONTINUE_STUFF_CONSTRUCTION"]
  material_type = "OBJECT"
  is_bag = true
  classes = ["BAG", "LITTLE_BAG", "SKIN_BAG"]
[LEATHER_BAG]
  name = "Sac de cuir"
  weight = 1500.0
  clutter = 2.0
  clutter_capacity = 7.0
  actions = ["DROP_STUFF","USE_AS_BAG","NOT_USE_AS_BAG", "CONTINUE_STUFF_CONSTRUCTION"]
  material_type = "OBJECT"
  is_bag = true
  classes = ["BAG", "LITTLE_BAG", "LEATHER_BAG"]
[TRAVOIS]
  name = "Travois"
  weight = 10000.0
  clutter = 10.0
  clutter_capacity = 12.0
  actions = ["DROP_STUFF","USE_AS_BAG","NOT_USE_AS_BAG", "CONTINUE_STUFF_CONSTRUCTION"]
  material_type = "OBJECT"
  is_bag = true
  classes = ["BAG"]
[CLOTH_BAG]
  name = "Sac de toile"
  weight = 1000.0
  clutter = 0.0
  clutter_capacity = 8.0
  actions = ["DROP_STUFF","USE_AS_BAG","NOT_USE_AS_BAG", "CONTINUE_STUFF_CONSTRUCTION"]
  material_type = "OBJECT"
  is_bag = true
  classes = ["BAG", "LITTLE_BAG", "CLOTH_BAG"]
[ANIMAL_SKIN_CLOTHES]
  name = "Habits de peaux"
  weight = 4000.0
  clutter = 3.0
  actions = ["DROP_STUFF", "USE_AS_ARMOR", "NOT_USE_AS_ARMOR", "CONTINUE_STUFF_CONSTRUCTION"]
  armor = true
  protect_estoc = 1
  protect_blunt = 5
  protect_sharp = 5
  classes = ["ARMOR", "CLOTHES"]
[LEATHER_CLOTHES]
  name = "Habits de cuir"
  weight = 2000.0
  clutter = 2.0
  actions = ["DROP_STUFF", "USE_AS_ARMOR", "NOT_USE_AS_ARMOR", "CONTINUE_STUFF_CONSTRUCTION"]
  armor = true
  protect_estoc = 5
  protect_blunt = 10
  protect_sharp = 10
  classes = ["ARMOR", "CLOTHES"]
[LEATHER_BRIGANDINE]
  name = "Brigandine de cuir"
  weight = 2250.0
  clutter = 3.0
  actions = ["DROP_STUFF", "USE_AS_ARMOR", "NOT_USE_AS_ARMOR", "CONTINUE_STUFF_CONSTRUCTION"]
  armor = true
  protect_estoc = 12
  protect_blunt = 15
  protect_sharp = 15
  classes = ["ARMOR", "CLOTHES", "LEATHER_ARMOR"]
[PRIMITIVE_WOOD_SHIELD]
  name = "Coque de bois"
  weight = 3500.0
  clutter = 5.0
  actions = ["DROP_STUFF", "USE_AS_SHIELD", "NOT_USE_AS_SHIELD", "CONTINUE_STUFF_CONSTRUCTION"]
  shield = true
  skills_bonus = ["shield_fight"]
  protect_estoc = 8
  protect_blunt = 5
  protect_sharp = 10
  classes = ["SHIELD"]
[WOOD_SHIELD]
  name = "Bouclier de bois"
  weight = 4000.0
  clutter = 4.0
  actions = ["DROP_STUFF", "USE_AS_SHIELD", "NOT_USE_AS_SHIELD", "CONTINUE_STUFF_CONSTRUCTION"]
  shield = true
  skills_bonus = ["shield_fight"]
  protect_estoc = 15
  protect_blunt = 10
  protect_sharp = 15
  classes = ["SHIELD"]
[WOOD_SPEAR]
  name = "Lance de bois"
  weight = 1000.0
  clutter = 1.0
  actions = ["DROP_STUFF", "CRAFT_STUFF_WITH_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
  weapon = true
  skills_bonus = ["spear_fight"]
  estoc = 10
  blunt = 0
  sharp = 0
  damages = 1.0
  classes = ["WEAPON", "SPEAR"]
[WOOD_MACE]
  name = "Massue"
  weight = 5000.0
  clutter = 2.0
  actions = ["DROP_STUFF", "CRAFT_STUFF_WITH_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
  weapon = true
  skills_bonus = ["mace_fight"]
  estoc = 0
  blunt = 10
  sharp = 0
  damages = 1.0
  classes = ["WEAPON", "SPEAR"]
[STONE_HAXE]
  name = "Hache de pierre"
  weight = 1000.0
  clutter = 1.0
  actions = ["DROP_STUFF", "CRAFT_STUFF_WITH_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
  weapon = true
  skills_bonus = ["haxe_fight"]
  estoc = 0
  blunt = 10
  sharp = 10
  damages = 1.0
  classes = ["WEAPON", "HAXE"]
[HARE]
  name = "Lièvre"
  weight = 3500.0
  clutter = 1.2
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "RABBIT"]
[PHEASANT]
  name = "Faisan"
  weight = 1500.0
  clutter = 1.0
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "BIRD"]
[RABBIT]
  name = "Lapin"
  weight = 2700.0
  clutter = 1.1
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "RABBIT"]
[PADRIDGE]
  name = "Perdrix"
  weight = 1500.0
  clutter = 1.0
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "BIRD"]
[DUCK]
  name = "Canard"
  weight = 2000.0
  clutter = 1.0
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "BIRD"]
[MOORHEN]
  name = "Poule d'eau"
  weight = 600.0
  clutter = 0.5
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "BIRD"]
[RAVEN]
  name = "Corbeau"
  weight = 650.0
  clutter = 0.5
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "BIRD"]
[FOX]
  name = "Renard"
  weight = 5500.0
  clutter = 2.0
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "LITTLE_PREDATOR"]
[MARTEN]
  name = "Fouine"
  weight = 2700.0
  clutter = 1.0
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "LITTLE_PREDATOR"]
[BOAR]
  name = "Sanglier"
  weight = 20000.0
  clutter = 10.0
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "MEDIUM_HERBIVORE"]
[DEER]
  name = "Chevreuil"
  weight = 18000.0
  clutter = 10.0
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "MEDIUM_HERBIVORE"]
[LITTLE_STATUETTE]
  name = "Petite statuette"
  weight = 700.0
  clutter = 0.5
  actions = ["DROP_STUFF", "CONTINUE_STUFF_CONSTRUCTION"]
  classes = ["CRAFT", "STATUETTE"]
