[PLASTIC_BOTTLE_1L]
  name = "Plastic bottle"
  filled_at = 0.0
  filled_unity = "L"
  weight = 0.1
  clutter = 1.0
  image = "bottle.jpg"
  actions = [
    {type = "FILL", fill_acceptable_types = ["LIQUID", "SANDY", "PASTY", "GAS"]}
  ]
  material_type = "OBJECT"
[STONE]
  name = "Stone"
  weight = 2000.0
  clutter = 1.0
  image = "stone.jpg"
  actions = [
    {type = "ATTACK_WITH"}
  ]
  material_type = "SOLID"
