[PLASTIC_BOTTLE_1L]
  name = "Plastic bottle"
  filled_at = 0.0
  filled_unity = "L"
  filled_capacity = 1.0
  weight = 0.1
  clutter = 1.0
  image = "bottle.jpg"
  actions = ["DROP_STUFF","FILL_STUFF","DRINK_STUFF","EMPTY_STUFF"]
  material_type = "OBJECT"
[STONE]
  name = "Stone"
  weight = 2000.0
  clutter = 1.0
  image = "stone.jpg"
  actions = ["DROP_STUFF"]
  material_type = "SOLID"
[LITTLE_SKIN_BAG]
  name = "Petit sac en peau"
  weight = 1200.0
  clutter = 0.0
  clutter_capacity = 5.0
  actions = ["DROP_STUFF","USE_AS_BAG","NOT_USE_AS_BAG"]
  material_type = "OBJECT"
  is_bag = true
[WOOD_SPEAR]
  name = "Lance de bois"
  weight = 1000.0
  clutter = 1.0
  actions = ["DROP_STUFF", "CRAFT_STUFF_WITH_STUFF"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
[WOOD_SPEAR_STRENGHTHENED]
  name = "Lance de bois renforcé"
  weight = 1000.0
  clutter = 1.0
  actions = ["DROP_STUFF", "CRAFT_STUFF_WITH_STUFF"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
# TODO BS 2019-10-10: living animals ? moving on zone ? farming !
[HARE]
  name = "Lièvre"
  weight = 3500.0
  clutter = 1.2
  actions = ["EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
[FAISAN]  # TODO: traduce
  name = "Faisan"
  weight = 1500.0
  clutter = 1.0
  actions = ["EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
[RABBIT]
  name = "Lapin"
  weight = 2700.0
  clutter = 1.1
  actions = ["EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
[PERDRIX]  # TODO: traduce
  name = "Perdrix"
  weight = 1500.0
  clutter = 1.0
  actions = ["EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
[DUCK]
  name = "Canard"
  weight = 2000.0
  clutter = 1.0
  actions = ["EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
[POULE]  # TODO: traduce
  name = "Poule d'eau"
  weight = 600.0
  clutter = 0.5
  actions = ["EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
[CORBEAU]  # TODO: traduce
  name = "Corbeau"
  weight = 650.0
  clutter = 0.5
  actions = ["EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
[FOX]
  name = "Renard"
  weight = 5500.0
  clutter = 2.0
  actions = ["EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
[FOUINE]  # TODO: traduce
  name = "Fouine"
  weight = 2700.0
  clutter = 1.0
  actions = ["EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
[SANGLIER]  # TODO: traduce
  name = "Sanglier"
  weight = 20000.0
  clutter = 10.0
  actions = ["EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
[CHEVREUIL]  # TODO: traduce
  name = "Chevreuil"
  weight = 18000.0
  clutter = 10.0
  actions = ["EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
