[CORPSE]  # system required
  name = "Corps"
  weight = 80000.0
  clutter = 15.0
  actions = ["DROP_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  material_type = "SOLID"

[LITTLE_SKIN_CANTEEN]
  name = "Petite gourde de peau"
  filled_value = 0.0
  filled_unity = "L"
  filled_capacity = 1.0
  weight = 1000.0
  clutter = 1.0
  actions = ["DROP_STUFF","FILL_STUFF","DRINK_STUFF","EMPTY_STUFF"]
  material_type = "OBJECT"
  classes = ["BOTTLE"]
[LITTLE_VEGETAL_CANTEEN]
  name = "Petite gourde végétale"
  filled_value = 0.0
  filled_unity = "L"
  filled_capacity = 1.0
  weight = 1500.0
  clutter = 1.5
  actions = ["DROP_STUFF","FILL_STUFF","DRINK_STUFF","EMPTY_STUFF"]
  material_type = "OBJECT"
  classes = ["BOTTLE"]
  illustration = "vegetal_canteen.png"
[RAW_CLAY_JAR]
  name = "Jarre de terre crue"
  weight = 5000.0
  clutter = 5
  actions = ["DROP_STUFF", "TRANSFORM_STUFF_TO_STUFF"]
  material_type = "OBJECT"
  classes = ["BOTTLE"]
  illustration = "raw_clay_jar.png"
[CLAY_JAR]
  name = "Jarre"
  filled_value = 0.0
  filled_unity = "L"
  filled_capacity = 30.0
  weight = 4500.0
  clutter = 5
  actions = ["DROP_STUFF","FILL_STUFF","DRINK_STUFF","EMPTY_STUFF"]
  material_type = "OBJECT"
  classes = ["BOTTLE"]
  illustration = "clay_jar.png"
[BASKETRY_BAG]
  name = "Sac végétal"
  weight = 1000.0
  clutter = 2.0
  clutter_capacity = 4.0
  actions = ["DROP_STUFF","USE_AS_BAG","NOT_USE_AS_BAG", "CONTINUE_STUFF_CONSTRUCTION"]
  material_type = "OBJECT"
  is_bag = true
  classes = ["BAG", "LITTLE_BAG", "BASKETRY_BAG"]
  illustration = "basketry_bag.png"
[SKIN_BAG]
  name = "Sac de peaux"
  weight = 2000.0
  clutter = 2.0
  clutter_capacity = 5.0
  actions = ["DROP_STUFF","USE_AS_BAG","NOT_USE_AS_BAG", "CONTINUE_STUFF_CONSTRUCTION"]
  material_type = "OBJECT"
  is_bag = true
  classes = ["BAG", "LITTLE_BAG", "SKIN_BAG"]
[LEATHER_BAG]
  name = "Sac de cuir"
  weight = 1500.0
  clutter = 2.0
  clutter_capacity = 7.0
  actions = ["DROP_STUFF","USE_AS_BAG","NOT_USE_AS_BAG", "CONTINUE_STUFF_CONSTRUCTION"]
  material_type = "OBJECT"
  is_bag = true
  classes = ["BAG", "LITTLE_BAG", "LEATHER_BAG"]
[TRAVOIS]
  name = "Travois"
  weight = 10000.0
  clutter = 5.0
  clutter_capacity = 12.0
  actions = ["DROP_STUFF","USE_AS_BAG","NOT_USE_AS_BAG", "CONTINUE_STUFF_CONSTRUCTION"]
  material_type = "OBJECT"
  is_bag = true
  classes = ["BAG"]
  illustration = "travois.png"
[CLOTH_BAG]
  name = "Sac de toile"
  weight = 1000.0
  clutter = 1.0
  clutter_capacity = 8.0
  actions = ["DROP_STUFF","USE_AS_BAG","NOT_USE_AS_BAG", "CONTINUE_STUFF_CONSTRUCTION"]
  material_type = "OBJECT"
  is_bag = true
  classes = ["BAG", "LITTLE_BAG", "CLOTH_BAG"]
[ANIMAL_SKIN_CLOTHES]
  name = "Habits de peaux"
  weight = 4000.0
  clutter = 3.0
  actions = ["DROP_STUFF", "USE_AS_ARMOR", "NOT_USE_AS_ARMOR", "CONTINUE_STUFF_CONSTRUCTION"]
  armor = true
  protect_estoc = 1
  protect_blunt = 5
  protect_sharp = 5
  classes = ["ARMOR", "CLOTHES"]
[LEATHER_CLOTHES]
  name = "Habits de cuir"
  weight = 2000.0
  clutter = 2.0
  actions = ["DROP_STUFF", "USE_AS_ARMOR", "NOT_USE_AS_ARMOR", "CONTINUE_STUFF_CONSTRUCTION"]
  armor = true
  protect_estoc = 5
  protect_blunt = 10
  protect_sharp = 10
  classes = ["ARMOR", "CLOTHES"]
[LEATHER_BRIGANDINE]
  name = "Brigandine de cuir"
  weight = 2250.0
  clutter = 3.0
  actions = ["DROP_STUFF", "USE_AS_ARMOR", "NOT_USE_AS_ARMOR", "CONTINUE_STUFF_CONSTRUCTION"]
  armor = true
  protect_estoc = 12
  protect_blunt = 15
  protect_sharp = 15
  classes = ["ARMOR", "CLOTHES", "LEATHER_ARMOR"]
[BRONZE_CUIRASS]
  name = "Cuirasse de bronze"
  weight = 5000.0
  clutter = 3.0
  actions = ["DROP_STUFF", "USE_AS_ARMOR", "NOT_USE_AS_ARMOR", "CONTINUE_STUFF_CONSTRUCTION"]
  armor = true
  protect_estoc = 25
  protect_blunt = 20
  protect_sharp = 25
  classes = ["ARMOR", "CLOTHES", "CUIRASS"]
  illustration = "bronze_cuirass.png"
[IRON_CUIRASS]
  name = "Cuirasse de fer"
  weight = 4000.0
  clutter = 3.0
  actions = ["DROP_STUFF", "USE_AS_ARMOR", "NOT_USE_AS_ARMOR", "CONTINUE_STUFF_CONSTRUCTION"]
  armor = true
  protect_estoc = 30
  protect_blunt = 25
  protect_sharp = 30
  classes = ["ARMOR", "CLOTHES", "CUIRASS"]
  illustration = "iron_cuirass.png"
[PRIMITIVE_WOOD_SHIELD]
  name = "Coque de bois"
  weight = 3500.0
  clutter = 5.0
  actions = ["DROP_STUFF", "USE_AS_SHIELD", "NOT_USE_AS_SHIELD", "CONTINUE_STUFF_CONSTRUCTION"]
  shield = true
  skills_bonus = ["shield_fight"]
  abilities = ["FIGHT"]
  protect_estoc = 8
  protect_blunt = 5
  protect_sharp = 10
  classes = ["SHIELD"]
[LEATHER_SHIELD]
  name = "Bouclier de cuir"
  weight = 3000.0
  clutter = 4.0
  actions = ["DROP_STUFF", "USE_AS_SHIELD", "NOT_USE_AS_SHIELD", "CONTINUE_STUFF_CONSTRUCTION"]
  shield = true
  skills_bonus = ["shield_fight"]
  abilities = ["FIGHT"]
  protect_estoc = 15
  protect_blunt = 10
  protect_sharp = 15
  classes = ["SHIELD"]
  illustration = "leather_shield.png"
[COPPER_SHIELD]
  name = "Bouclier de cuivre"
  weight = 3500.0
  clutter = 4.0
  actions = ["DROP_STUFF", "USE_AS_SHIELD", "NOT_USE_AS_SHIELD", "CONTINUE_STUFF_CONSTRUCTION"]
  shield = true
  skills_bonus = ["shield_fight"]
  abilities = ["FIGHT"]
  protect_estoc = 20
  protect_blunt = 20
  protect_sharp = 25
  classes = ["SHIELD"]
  illustration = "copper_shield.png"
[BRONZE_SHIELD]
  name = "Bouclier de bronze"
  weight = 3000.0
  clutter = 4.0
  actions = ["DROP_STUFF", "USE_AS_SHIELD", "NOT_USE_AS_SHIELD", "CONTINUE_STUFF_CONSTRUCTION"]
  shield = true
  skills_bonus = ["shield_fight"]
  abilities = ["FIGHT"]
  protect_estoc = 25
  protect_blunt = 25
  protect_sharp = 30
  classes = ["SHIELD"]
  illustration = "bronze_shield.png"
[IRON_SHIELD_HEATER]
  name = "Écu"
  weight = 1800.0
  clutter = 4.0
  actions = ["DROP_STUFF", "USE_AS_SHIELD", "NOT_USE_AS_SHIELD", "CONTINUE_STUFF_CONSTRUCTION"]
  shield = true
  skills_bonus = ["shield_fight"]
  abilities = ["FIGHT"]
  protect_estoc = 35
  protect_blunt = 35
  protect_sharp = 40
  classes = ["SHIELD"]
[STONE_SPEAR]
  name = "Lance de pierre"
  weight = 1200.0
  clutter = 1.0
  actions = ["DROP_STUFF", "CRAFT_STUFF_WITH_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT", "BORDER_FISHING"]
  weapon = true
  skills_bonus = ["spear_fight"]
  estoc = 10
  blunt = 0
  sharp = 0
  damages = 1.0
  classes = ["WEAPON", "SPEAR"]
  illustration = "stone_spear.png"
[HUNT_BOW]
  name = "Arc de chasse"
  weight = 1000.0
  clutter = 1.0
  actions = ["DROP_STUFF", "CRAFT_STUFF_WITH_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT", "BORDER_FISHING"]
  weapon = true
  skills_bonus = ["bow_fight"]
  estoc = 6
  blunt = 0
  sharp = 0
  damages = 0.8
  classes = ["WEAPON", "BOW"]
  illustration = "hunt_bow.png"
[COPPER_SPEAR]
  name = "Lance de cuivre"
  weight = 1000.0
  clutter = 1.0
  actions = ["DROP_STUFF", "CRAFT_STUFF_WITH_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON", "CONTINUE_STUFF_CONSTRUCTION"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT", "BORDER_FISHING"]
  weapon = true
  skills_bonus = ["spear_fight"]
  estoc = 20
  blunt = 0
  sharp = 0
  damages = 2.0
  classes = ["WEAPON", "SPEAR"]
  illustration = "copper_spear.png"
[BRONZE_SPEAR]
  name = "Lance de bronze"
  weight = 1000.0
  clutter = 1.0
  actions = ["DROP_STUFF", "CRAFT_STUFF_WITH_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON", "CONTINUE_STUFF_CONSTRUCTION"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT", "BORDER_FISHING"]
  weapon = true
  skills_bonus = ["spear_fight"]
  estoc = 25
  blunt = 0
  sharp = 0
  damages = 2.2
  classes = ["WEAPON", "SPEAR"]
  illustration = "bronze_spear.png"
[IRON_SPEAR]
  name = "Lance de fer"
  weight = 800.0
  clutter = 1.0
  actions = ["DROP_STUFF", "CRAFT_STUFF_WITH_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON", "CONTINUE_STUFF_CONSTRUCTION"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT", "BORDER_FISHING"]
  weapon = true
  skills_bonus = ["spear_fight"]
  estoc = 30
  blunt = 0
  sharp = 0
  damages = 2.8
  classes = ["WEAPON", "SPEAR"]
  illustration = "iron_spear.png"
[WOOD_MACE]
  name = "Massue"
  weight = 5000.0
  clutter = 2.0
  actions = ["DROP_STUFF", "CRAFT_STUFF_WITH_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
  weapon = true
  skills_bonus = ["mace_fight"]
  estoc = 0
  blunt = 10
  sharp = 0
  damages = 1.0
  classes = ["WEAPON", "MACE"]
  illustration = "wood_mace.png"
[STONE_HAXE]
  name = "Hache de pierre"
  weight = 1200.0
  clutter = 1.0
  actions = ["DROP_STUFF", "CRAFT_STUFF_WITH_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
  weapon = true
  skills_bonus = ["haxe_fight"]
  estoc = 0
  blunt = 10
  sharp = 10
  damages = 1.0
  classes = ["WEAPON", "HAXE"]
  illustration = "stone_axe.png"
  bonuses = {COLLECT_RESOURCE={WOOD=0.70}}
[COPPER_HAXE]
  name = "Hache de guerre (cuivre)"
  weight = 1000.0
  clutter = 1.0
  actions = ["DROP_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON", "CONTINUE_STUFF_CONSTRUCTION"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
  weapon = true
  skills_bonus = ["haxe_fight"]
  estoc = 0
  blunt = 20
  sharp = 20
  damages = 2.0
  classes = ["WEAPON", "HAXE"]
  illustration = "clutter_axe.png"
  bonuses = {COLLECT_RESOURCE={WOOD=0.65}}
[BRONZE_HAXE]
  name = "Hache de guerre (bronze)"
  weight = 1000.0
  clutter = 1.0
  actions = ["DROP_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON", "CONTINUE_STUFF_CONSTRUCTION"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
  weapon = true
  skills_bonus = ["haxe_fight"]
  estoc = 0
  blunt = 25
  sharp = 25
  damages = 2.2
  classes = ["WEAPON", "HAXE"]
  illustration = "bronze_axe.png"
  bonuses = {COLLECT_RESOURCE={WOOD=0.60}}
[IRON_HAXE]
  name = "Hache de guerre (fer)"
  weight = 900.0
  clutter = 1.0
  actions = ["DROP_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON", "CONTINUE_STUFF_CONSTRUCTION"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
  weapon = true
  skills_bonus = ["haxe_fight"]
  estoc = 0
  blunt = 30
  sharp = 30
  damages = 2.8
  classes = ["WEAPON", "HAXE"]
  illustration = "iron_axe.png"
  bonuses = {COLLECT_RESOURCE={WOOD=0.55}}
[STONE_DAGGER]
  name = "Dague de pierre"
  weight = 400.0
  clutter = 0.3
  actions = ["DROP_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON", "CONTINUE_STUFF_CONSTRUCTION"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
  weapon = true
  skills_bonus = ["dagger_fight"]
  estoc = 3
  blunt = 0
  sharp = 3
  damages = 1.0
  classes = ["WEAPON", "DAGGER"]
  illustration = "stone_dagger.png"
[COPPER_DAGGER]
  name = "Dague de cuivre"
  weight = 500.0
  clutter = 0.3
  actions = ["DROP_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON", "CONTINUE_STUFF_CONSTRUCTION"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
  weapon = true
  skills_bonus = ["dagger_fight"]
  estoc = 8
  blunt = 2
  sharp = 7
  damages = 1.5
  classes = ["WEAPON", "DAGGER"]
  illustration = "copper_dagger.png"
[BRONZE_DAGGER]
  name = "Dague de bronze"
  weight = 500.0
  clutter = 0.3
  actions = ["DROP_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON", "CONTINUE_STUFF_CONSTRUCTION"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
  weapon = true
  skills_bonus = ["dagger_fight"]
  estoc = 8
  blunt = 2
  sharp = 8
  damages = 1.6
  classes = ["WEAPON", "DAGGER"]
  illustration = "bronze_dagger.png"
[IRON_DAGGER]
  name = "Dague de fer"
  weight = 400.0
  clutter = 0.3
  actions = ["DROP_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON", "CONTINUE_STUFF_CONSTRUCTION"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
  weapon = true
  skills_bonus = ["dagger_fight"]
  estoc = 12
  blunt = 5
  sharp = 12
  damages = 1.8
  classes = ["WEAPON", "DAGGER"]
  illustration = "iron_dagger.png"
[HARE]
  name = "Lièvre"
  weight = 3500.0
  clutter = 1.2
  actions = ["DROP_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "RABBIT"]
  illustration = "hare.png"
[PHEASANT]
  name = "Faisan"
  weight = 1500.0
  clutter = 1.0
  actions = ["DROP_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "BIRD"]
  illustration = "pheasant.png"
[RABBIT]
  name = "Lapin"
  weight = 2700.0
  clutter = 1.1
  actions = ["DROP_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "RABBIT"]
[PADRIDGE]
  name = "Perdrix"
  weight = 1500.0
  clutter = 1.0
  actions = ["DROP_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "BIRD"]
[DUCK]
  name = "Canard"
  weight = 2000.0
  clutter = 1.0
  actions = ["DROP_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "BIRD"]
[MOORHEN]
  name = "Poule d'eau"
  weight = 600.0
  clutter = 0.5
  actions = ["DROP_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "BIRD"]
  illustration = "moorhen.png"
[RAVEN]
  name = "Corbeau"
  weight = 650.0
  clutter = 0.5
  actions = ["DROP_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "BIRD"]
[FOX]
  name = "Renard"
  weight = 5500.0
  clutter = 2.0
  actions = ["DROP_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "LITTLE_PREDATOR"]
[MARTEN]
  name = "Fouine"
  weight = 2700.0
  clutter = 1.0
  actions = ["DROP_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "LITTLE_PREDATOR"]
[BOAR]
  name = "Sanglier"
  weight = 20000.0
  clutter = 10.0
  actions = ["DROP_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "MEDIUM_HERBIVORE"]
  illustration = "boar.png"
[DEER]
  name = "Chevreuil"
  weight = 18000.0
  clutter = 10.0
  actions = ["DROP_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "MEDIUM_HERBIVORE"]
  illustration = "deer.png"
[LITTLE_STATUETTE]
  name = "Petite statuette"
  weight = 700.0
  clutter = 0.5
  actions = ["DROP_STUFF", "CONTINUE_STUFF_CONSTRUCTION"]
  classes = ["CRAFT", "STATUETTE"]
  illustration = "venus.png"
[SPINDLE]
  name = "Fuseau"
  weight = 500.0
  clutter = 0.1
  actions = ["DROP_STUFF", "CONTINUE_STUFF_CONSTRUCTION"]
  classes = ["CRAFT"]
  illustration = "spindles.png"
  abilities = ["SPIN1"]
[ROUET]
  name = "Rouet"
  weight = 5000.0
  clutter = 3.0
  actions = ["DROP_STUFF", "CONTINUE_STUFF_CONSTRUCTION"]
  classes = ["CRAFT"]
  illustration = "rouet.png"
  abilities = ["SPIN2"]
[LITTLE_FISHING_NET]
  name = "Petit filet de pêche"
  weight = 5000.0
  clutter = 2.0
  actions = ["DROP_STUFF", "CONTINUE_STUFF_CONSTRUCTION"]
  abilities = ["BORDER_FISHING"]
  classes = ["CRAFT"]
  illustration = "littlefishnet.png"
[MORTIER_PILON]
  name = "Mortier et Pilon"
  weight = 10000.0
  clutter = 2.0
  actions = ["DROP_STUFF", "CONTINUE_STUFF_CONSTRUCTION"]
  classes = ["CRAFT"]
  abilities = ["GRIND"]
  illustration = "Mortier_Pillon.png"
[STONE_ANVIL]
  name = "Enclume de pierre"
  weight = 75000.0
  clutter = 15.0
  actions = ["DROP_STUFF", "CONTINUE_STUFF_CONSTRUCTION"]
  classes = ["CRAFT"]
  abilities = ["HAMMERING1"]
  illustration = "stone_anvil.png"
[IRON_ANVIL]
  name = "Enclume"
  weight = 95000.0
  clutter = 10.0
  actions = ["DROP_STUFF", "CONTINUE_STUFF_CONSTRUCTION"]
  classes = ["CRAFT"]
  illustration = "anvil.png"
  abilities = ["HAMMERING1", "HAMMERING2"]
[WOOD_QUARRY_TOOLS]
  name = "Outils de carrière (bois)"
  weight = 1000.0
  clutter = 0.5
  actions = ["DROP_STUFF"]
  classes = ["CRAFT"]
  illustration = "wood_quarry_tools.png"
  abilities = []
  bonuses = {COLLECT_RESOURCE={RAW_STONE=0.9}}
[IRON_QUARRY_TOOLS]
  name = "Outils de carrière (fer)"
  weight = 2000.0
  clutter = 0.5
  actions = ["DROP_STUFF"]
  classes = ["CRAFT"]
  illustration = "iron_quarry_tools.png"
  abilities = []
  bonuses = {COLLECT_RESOURCE={RAW_STONE=0.7}}
[STONE_SICKLE]
  name = "Faucille (pierre)"
  weight = 800.0
  clutter = 0.2
  actions = ["DROP_STUFF"]
  classes = ["CRAFT"]
  illustration = "stone_sickle.png"
  abilities = []
  bonuses = {COLLECT_RESOURCE={VEGETAL_FIBER=0.7}}
[COPPER_SICKLE]
  name = "Faucille (cuivre)"
  weight = 700.0
  clutter = 0.2
  actions = ["DROP_STUFF"]
  classes = ["CRAFT"]
  abilities = []
  bonuses = {COLLECT_RESOURCE={VEGETAL_FIBER=0.6}}
[BRONZE_SICKLE]
  name = "Faucille (bronze)"
  weight = 600.0
  clutter = 0.2
  actions = ["DROP_STUFF"]
  classes = ["CRAFT"]
  abilities = []
  bonuses = {COLLECT_RESOURCE={VEGETAL_FIBER=0.55}}
[IRON_SICKLE]
  name = "Faucille (fer)"
  weight = 500.0
  clutter = 0.2
  actions = ["DROP_STUFF"]
  classes = ["CRAFT"]
  abilities = []
  bonuses = {COLLECT_RESOURCE={VEGETAL_FIBER=0.50}}
[BRONZE_SCYTHE]
  name = "Faux (bronze)"
  weight = 1200.0
  clutter = 0.2
  actions = ["DROP_STUFF"]
  classes = ["CRAFT"]
  abilities = []
  bonuses = {COLLECT_RESOURCE={VEGETAL_FIBER=0.40}}
[IRON_SCYTHE]
  name = "Faucille (fer)"
  weight = 1000.0
  clutter = 0.2
  actions = ["DROP_STUFF"]
  classes = ["CRAFT"]
  abilities = []
  bonuses = {COLLECT_RESOURCE={VEGETAL_FIBER=0.30}}
