[PLASTIC_BOTTLE_1L]
  name = "Plastic bottle"
  filled_at = 0.0
  filled_unity = "L"
  weight = 0.1
  clutter = 1.0
  image = "bottle.jpg"
[STONE]
  name = "Stone"
  weight = 2000.0
  clutter = 1.0
  image = "stone.jpg"
