[PLASTIC_BOTTLE_1L]
  name = "Plastic bottle"
  filled_at = 0.0
  filled_unity = "L"
  filled_capacity = 1.0
  weight = 0.1
  clutter = 1.0
  image = "bottle.jpg"
  actions = ["DROP_STUFF","FILL_STUFF","DRINK_STUFF","EMPTY_STUFF"]
  material_type = "OBJECT"
[STONE]
  name = "Stone"
  weight = 2000.0
  clutter = 1.0
  image = "stone.jpg"
  actions = ["DROP_STUFF"]
  material_type = "SOLID"
[LITTLE_SKIN_BAG]
  name = "Petit sac en peau"
  weight = 1200.0
  clutter = 0.0
  clutter_capacity = 5.0
  actions = ["DROP_STUFF","USE_AS_BAG","NOT_USE_AS_BAG"]
  material_type = "OBJECT"
  is_bag = true
[WOOD_SPEAR]
  name = "Lance de bois"
  weight = 1000.0
  clutter = 1.0
  actions = ["DROP_STUFF"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
# TODO BS 2019-10-10: living animals ? moving on zone ? farming !
[HARE]
  name = "Lièvre"
  weight = 3500.0
  clutter = 1.0
  actions = ["EAT_STUFF"]
  generate_resources = [
    {require_one_of_ability=["HEAT_UP_LOW_TEMP"], resource_id="COOKED_MEAT", quantity=1200.0},
    {require_one_of_ability=[], resource_id="RAW_MEAT", quantity=1300.0},
  ]
