[PLASTIC_BOTTLE_1L]
  name = "Plastic bottle"
  filled_at = 0.0
  filled_unity = "L"
  filled_capacity = 1.0
  weight = 0.1
  clutter = 1.0
  image = "bottle.jpg"
  action_properties = [
    {type = "FILL_STUFF", acceptable_material_types = ["LIQUID", "SANDY", "PASTY", "GAS"]},
    {type = "DRINK_STUFF"},
    {type = "EMPTY_STUFF"}
  ]
  material_type = "OBJECT"
[STONE]
  name = "Stone"
  weight = 2000.0
  clutter = 1.0
  image = "stone.jpg"
  action_properties = [
    {type = "ATTACK_CHARACTER_WITH"}
  ]
  material_type = "SOLID"
