[CORPSE]  # system required
  name = "Corps"
  weight = 80000.0
  clutter = 15.0
  actions = ["DROP_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  material_type = "SOLID"

[PLASTIC_BOTTLE_1L]
  name = "Plastic bottle"
  filled_at = 0.0
  filled_unity = "L"
  filled_capacity = 1.0
  weight = 0.1
  clutter = 1.0
  image = "bottle.jpg"
  actions = ["DROP_STUFF","FILL_STUFF","DRINK_STUFF","EMPTY_STUFF"]
  material_type = "OBJECT"
  classes = ["BOTTLE"]

[LITTLE_SKIN_CANTEEN]
  name = "Petite gourde de peau"
  filled_at = 0.0
  filled_unity = "L"
  filled_capacity = 1.0
  weight = 0.1
  clutter = 1.0
  actions = ["DROP_STUFF","FILL_STUFF","DRINK_STUFF","EMPTY_STUFF"]
  material_type = "OBJECT"
  classes = ["BOTTLE"]
[STONE]
  name = "Stone"
  weight = 2000.0
  clutter = 1.0
  image = "stone.jpg"
  actions = ["DROP_STUFF"]
  material_type = "SOLID"
  weapon = true
[LITTLE_BASKETRY_BAG]
  name = "Petit sac végétal"
  weight = 1000.0
  clutter = 0.0
  clutter_capacity = 4.0
  actions = ["DROP_STUFF","USE_AS_BAG","NOT_USE_AS_BAG"]
  material_type = "OBJECT"
  is_bag = true
  classes = ["BAG", "LITTLE_BAG", "BASKETRY_BAG"]
[LITTLE_SKIN_BAG]
  name = "Petit sac en peau"
  weight = 1200.0
  clutter = 0.0
  clutter_capacity = 5.0
  actions = ["DROP_STUFF","USE_AS_BAG","NOT_USE_AS_BAG"]
  material_type = "OBJECT"
  is_bag = true
  classes = ["BAG", "LITTLE_BAG", "SKIN_BAG"]
[ANIMAL_SKIN_COAT]
  name = "Veste de peaux animales"
  weight = 2000.0
  clutter = 3.0
  actions = ["DROP_STUFF", "USE_AS_ARMOR", "NOT_USE_AS_ARMOR", "CONTINUE_STUFF_CONSTRUCTION"]
  armor = true
  protect_estoc = 5
  protect_blunt = 5
  protect_sharp = 5
  classes = ["ARMOR", "COAT"]
[PRIMITIVE_WOOD_SHIELD]
  name = "Bouclier de planche"
  weight = 3500.0
  clutter = 5.0
  actions = ["DROP_STUFF", "USE_AS_SHIELD", "NOT_USE_AS_SHIELD", "CONTINUE_STUFF_CONSTRUCTION"]
  shield = true
  skills_bonus = ["shield_fight"]
  protect_estoc = 10
  protect_blunt = 10
  protect_sharp = 10
  classes = ["SHIELD"]
[WOOD_SPEAR]
  name = "Lance de bois"
  weight = 1000.0
  clutter = 1.0
  actions = ["DROP_STUFF", "CRAFT_STUFF_WITH_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
  weapon = true
  skills_bonus = ["spear_fight"]
  estoc = 10
  blunt = 0
  sharp = 0
  damages = 1.0
  classes = ["WEAPON", "SPEAR"]
[WOOD_SPEAR_STONE]
  name = "Lance de bois et pierre"
  weight = 1200.0
  clutter = 1.0
  actions = ["DROP_STUFF", "CRAFT_STUFF_WITH_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
  weapon = true
  skills_bonus = ["spear_fight"]
  estoc = 12
  blunt = 0
  sharp = 0
  damages = 1.1
  classes = ["WEAPON", "SPEAR"]
[WOOD_SPEAR_STRENGHTHENED]
  name = "Lance de bois renforcé"
  weight = 1000.0
  clutter = 1.0
  actions = ["DROP_STUFF", "CRAFT_STUFF_WITH_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
  weapon = true
  skills_bonus = ["spear_fight"]
  estoc = 11
  blunt = 0
  sharp = 0
  damages = 1.1
  classes = ["WEAPON", "SPEAR"]
[WOOD_ASSEGAI]
  name = "Sagaie de bois"
  weight = 500.0
  clutter = 1.0
  actions = ["DROP_STUFF", "CRAFT_STUFF_WITH_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
  weapon = true
  skills_bonus = ["spear_fight"]
  estoc = 10
  blunt = 0
  sharp = 0
  damages = 1.0
  classes = ["WEAPON", "SPEAR"]
[STONE_HAXE]
  name = "Hache de pierre"
  weight = 1000.0
  clutter = 1.0
  actions = ["DROP_STUFF", "CRAFT_STUFF_WITH_STUFF", "USE_AS_WEAPON", "NOT_USE_AS_WEAPON"]
  abilities = ["HUNT_SMALL_GAME", "FIGHT"]
  weapon = true
  skills_bonus = ["haxe_fight"]
  estoc = 0
  blunt = 10
  sharp = 10
  damages = 1.0
  classes = ["WEAPON", "HAXE"]
# TODO BS 2019-10-10: living animals ? moving on zone ? farming !
[HARE]
  name = "Lièvre"
  weight = 3500.0
  clutter = 1.2
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "RABBIT"]
[PHEASANT]
  name = "Faisan"
  weight = 1500.0
  clutter = 1.0
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "BIRD"]
[RABBIT]
  name = "Lapin"
  weight = 2700.0
  clutter = 1.1
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "RABBIT"]
[PADRIDGE]
  name = "Perdrix"
  weight = 1500.0
  clutter = 1.0
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "BIRD"]
[DUCK]
  name = "Canard"
  weight = 2000.0
  clutter = 1.0
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "BIRD"]
[MOORHEN]
  name = "Poule d'eau"
  weight = 600.0
  clutter = 0.5
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "BIRD"]
[RAVEN]
  name = "Corbeau"
  weight = 650.0
  clutter = 0.5
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "BIRD"]
[FOX]
  name = "Renard"
  weight = 5500.0
  clutter = 2.0
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "LITTLE_PREDATOR"]
[MARTEN]
  name = "Fouine"
  weight = 2700.0
  clutter = 1.0
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "LITTLE_PREDATOR"]
[BOAR]
  name = "Sanglier"
  weight = 20000.0
  clutter = 10.0
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "MEDIUM_HERBIVORE"]
[DEER]
  name = "Chevreuil"
  weight = 18000.0
  clutter = 10.0
  actions = ["DROP_STUFF", "EAT_STUFF", "TRANSFORM_STUFF_TO_RESOURCES"]
  classes = ["ANIMAL", "MEDIUM_HERBIVORE"]
[LITTLE_STATUETTE]
  name = "Petite statuette"
  weight = 700.0
  clutter = 0.5
  actions = ["DROP_STUFF", "CONTINUE_STUFF_CONSTRUCTION"]
  classes = ["CRAFT", "STATUETTE"]
