[ZONE_PROPERTIES]
  [ZONE_PROPERTIES.BEACH]
    [ZONE_PROPERTIES.BEACH.GENERATION]
      count = 15

      [ZONE_PROPERTIES.BEACH.GENERATION.STUFF]
        [ZONE_PROPERTIES.BEACH.GENERATION.STUFF.PLASTIC_BOTTLE_1L]
          probability = 100.0
          filled_at = 0.0
  [ZONE_PROPERTIES.PLAIN]
    [ZONE_PROPERTIES.PLAIN.GENERATION]
      count = 15

      [ZONE_PROPERTIES.PLAIN.GENERATION.STUFF]
        [ZONE_PROPERTIES.PLAIN.GENERATION.STUFF.STONE]
          probability = 100.0
