[ZONE_PROPERTIES]
  [ZONE_PROPERTIES.BEACH]
    move_cost = 4.0

    [ZONE_PROPERTIES.BEACH.GENERATION]
      count = 1

      [ZONE_PROPERTIES.BEACH.GENERATION.STUFF]
        [ZONE_PROPERTIES.BEACH.GENERATION.STUFF.PLASTIC_BOTTLE_1L]
          probability = 100.0
          filled_at = 0.0
          # TODO BS 2019-07-04: add filled_with_resource, and change structure to permit multipler same stuff id

    [ZONE_PROPERTIES.BEACH.RESOURCES]
      [ZONE_PROPERTIES.BEACH.RESOURCES.PAGUROIDEA]  # bernard l'hermite, u
        probability = 100.0  # probability to be available on x,y zone at world init
        maximum = 500.0  # maximum quantity on x,y zone
        regeneration = 50.0  # quatity generation per turn
      [ZONE_PROPERTIES.BEACH.RESOURCES.MYTILIDA]  # moule, g
        probability = 100.0
        maximum = 100000.0
        regeneration = 5000.0
      [ZONE_PROPERTIES.BEACH.RESOURCES.COCONUT]
        probability = 100.0
        maximum = 500.0
        regeneration = 20.0

    [ZONE_PROPERTIES.BEACH.STUFFS]
      [ZONE_PROPERTIES.BEACH.STUFFS.HARE]  # bernard l'hermite, u
        probability = 80.0  # probability to be available on x,y zone at world init
        maximum = 100.0  # maximum quantity on x,y zone (u)
        regeneration = 5.0  # quatity generation per turn
      [ZONE_PROPERTIES.BEACH.STUFFS.RABBIT]
        probability = 80.0
        maximum = 50.0
        regeneration = 5.0
      [ZONE_PROPERTIES.BEACH.STUFFS.FOX]
        probability = 80.0
        maximum = 10.0
        regeneration = 1.0

  [ZONE_PROPERTIES.PLAIN]
    move_cost = 4.0

    [ZONE_PROPERTIES.PLAIN.STUFFS]
      [ZONE_PROPERTIES.PLAIN.STUFFS.HARE]  # bernard l'hermite, u
        probability = 80.0  # probability to be available on x,y zone at world init
        maximum = 100.0  # maximum quantity on x,y zone (u)
        regeneration = 5.0  # quatity generation per turn
      [ZONE_PROPERTIES.PLAIN.STUFFS.RABBIT]
        probability = 80.0
        maximum = 50.0
        regeneration = 5.0
      [ZONE_PROPERTIES.PLAIN.STUFFS.MOORHEN]
        probability = 100.0
        maximum = 350.0
        regeneration = 10.0
      [ZONE_PROPERTIES.PLAIN.STUFFS.FOX]
        probability = 80.0
        maximum = 5.0
        regeneration = 1.0
      [ZONE_PROPERTIES.PLAIN.STUFFS.MARTEN]
        probability = 80.0
        maximum = 30.0
        regeneration = 1.0
      [ZONE_PROPERTIES.PLAIN.STUFFS.BOAR]
        probability = 80.0
        maximum = 50.0
        regeneration = 2.0
      [ZONE_PROPERTIES.PLAIN.STUFFS.DEER]
        probability = 20.0
        maximum = 50.0
        regeneration = 1.0

    [ZONE_PROPERTIES.PLAIN.RESOURCES]
      [ZONE_PROPERTIES.PLAIN.RESOURCES.GRAMINEAE]
        probability = 100.0  # probability to be available on x,y zone at world init
        maximum = 10000.0  # maximum quantity on x,y zone
        regeneration = 100.0  # quatity generation per turn

    [ZONE_PROPERTIES.PLAIN.GENERATION]
      count = 15

      [ZONE_PROPERTIES.PLAIN.GENERATION.STUFF]
        [ZONE_PROPERTIES.PLAIN.GENERATION.STUFF.STONE]
          probability = 100.0

  [ZONE_PROPERTIES.SEA]
    move_cost = 6.0

    [ZONE_PROPERTIES.SEA.GENERATION]
      count = 0

  [ZONE_PROPERTIES.MOUNTAIN]
    move_cost = 8.0


    [ZONE_PROPERTIES.MOUNTAIN.STUFFS]
      [ZONE_PROPERTIES.MOUNTAIN.STUFFS.HARE]
        probability = 50.0  # probability to be available on x,y zone at world init
        maximum = 20.0  # maximum quantity on x,y zone (u)
        regeneration = 1.0  # quatity generation per turn
      [ZONE_PROPERTIES.MOUNTAIN.STUFFS.FOX]
        probability = 50.0
        maximum = 2.0
        regeneration = 1.0
      [ZONE_PROPERTIES.MOUNTAIN.STUFFS.MARTEN]
        probability = 20.0
        maximum = 10.0
        regeneration = 1.0
      [ZONE_PROPERTIES.MOUNTAIN.STUFFS.BOAR]
        probability = 60.0
        maximum = 30.0
        regeneration = 1.0
      [ZONE_PROPERTIES.MOUNTAIN.STUFFS.DEER]
        probability = 90.0
        maximum = 100.0
        regeneration = 2.0

    [ZONE_PROPERTIES.MOUNTAIN.GENERATION]
      count = 0

  [ZONE_PROPERTIES.JUNGLE]
    move_cost = 8.0

    [ZONE_PROPERTIES.JUNGLE.RESOURCES]
      [ZONE_PROPERTIES.JUNGLE.RESOURCES.BERRY]
        probability = 100.0  # probability to be available on x,y zone at world init
        maximum = 5000.0  # maximum quantity on x,y zone
        regeneration = 10.0  # quatity generation per turn
      [ZONE_PROPERTIES.JUNGLE.RESOURCES.NUT]
        probability = 100.0
        maximum = 15000.0
        regeneration = 5.0
      [ZONE_PROPERTIES.JUNGLE.RESOURCES.BANANA]
        probability = 100.0
        maximum = 3000.0
        regeneration = 50.0

    [ZONE_PROPERTIES.JUNGLE.STUFFS]
      # TODO: ANIMAUX DE LA JUNGLE
      [ZONE_PROPERTIES.JUNGLE.STUFFS.HARE]  # bernard l'hermite, u
        probability = 80.0  # probability to be available on x,y zone at world init
        maximum = 100.0  # maximum quantity on x,y zone (u)
        regeneration = 5.0  # quatity generation per turn
      [ZONE_PROPERTIES.JUNGLE.STUFFS.RABBIT]
        probability = 80.0
        maximum = 50.0
        regeneration = 5.0
      [ZONE_PROPERTIES.JUNGLE.STUFFS.MOORHEN]
        probability = 100.0
        maximum = 350.0
        regeneration = 10.0
      [ZONE_PROPERTIES.JUNGLE.STUFFS.FOX]
        probability = 80.0
        maximum = 5.0
        regeneration = 1.0
      [ZONE_PROPERTIES.JUNGLE.STUFFS.MARTEN]
        probability = 80.0
        maximum = 30.0
        regeneration = 1.0
      [ZONE_PROPERTIES.JUNGLE.STUFFS.BOAR]
        probability = 80.0
        maximum = 50.0
        regeneration = 2.0
      [ZONE_PROPERTIES.JUNGLE.STUFFS.DEER]
        probability = 20.0
        maximum = 50.0
        regeneration = 1.0

    [ZONE_PROPERTIES.JUNGLE.GENERATION]
      count = 0

  [ZONE_PROPERTIES.HILL]
    move_cost = 5.0

    [ZONE_PROPERTIES.HILL.RESOURCES]
      [ZONE_PROPERTIES.HILL.RESOURCES.GRAMINEAE]
        probability = 100.0  # probability to be available on x,y zone at world init
        maximum = 50000.0  # maximum quantity on x,y zone
        regeneration = 10.0  # quatity generation per turn

    [ZONE_PROPERTIES.HILL.STUFFS]
      [ZONE_PROPERTIES.HILL.STUFFS.HARE]  # bernard l'hermite, u
        probability = 80.0  # probability to be available on x,y zone at world init
        maximum = 100.0  # maximum quantity on x,y zone (u)
        regeneration = 5.0  # quatity generation per turn
      [ZONE_PROPERTIES.HILL.STUFFS.RABBIT]
        probability = 80.0
        maximum = 50.0
        regeneration = 5.0
      [ZONE_PROPERTIES.HILL.STUFFS.MOORHEN]
        probability = 100.0
        maximum = 350.0
        regeneration = 10.0
      [ZONE_PROPERTIES.HILL.STUFFS.FOX]
        probability = 80.0
        maximum = 5.0
        regeneration = 1.0
      [ZONE_PROPERTIES.HILL.STUFFS.MARTEN]
        probability = 80.0
        maximum = 30.0
        regeneration = 1.0
      [ZONE_PROPERTIES.HILL.STUFFS.BOAR]
        probability = 80.0
        maximum = 50.0
        regeneration = 2.0
      [ZONE_PROPERTIES.HILL.STUFFS.DEER]
        probability = 20.0
        maximum = 50.0
        regeneration = 1.0

    [ZONE_PROPERTIES.HILL.GENERATION]
      count = 0

[TILES]
  [TILES.LEAF_TREE]
    produce = [
      {resource="WOOD", start_capacity=2.0, regeneration=0.001},
      {resource="BRANCHES", start_capacity=1.0, regeneration=0.001},
    ]
  [TILES.TROPICAL_TREE]
    produce = [
      {resource="WOOD", start_capacity=2.5, regeneration=0.002},
      {resource="BRANCHES", start_capacity=1.5, regeneration=0.002},
    ]
  [TILES.DEAD_TREE]
    produce = [
      {resource="WOOD", start_capacity=2.0, regeneration=0.0},
      {resource="BRANCHES", start_capacity=1.0, regeneration=0.0},
    ]
