language: python
dist: xenial
services:
  - postgresql
python:
  - "3.7"
#  - "3.8"
install:
  - "python setup.py develop"
  - "pip install -e '.[dev]'"
before_script:
  - psql -c 'create database rolling;' -U postgres
script: pytest tests --disable-pytest-warnings
