language: python
dist: xenial
services:
  - postgresql
python:
  - "3.8"
install:
  - "pip install -r requirements.txt"
  - "pip install -e '.[dev]'"
  - "python setup.py develop"
  - "cp server.ini.tpl server.ini"
before_script:
  - psql -c 'CREATE DATABASE rolling_test;' -U postgres
  - psql -c "CREATE USER rolling WITH PASSWORD 'rolling';" -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE rolling_test TO rolling;' -U postgres
script: pytest tests --disable-pytest-warnings -vvvvv
