[package]
name = "rrolling"
version = "0.1.0"
edition = "2021"

[lib]
name = "rrolling"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.1", features = ["extension-module"] }
log = "~0.4"
pyo3-log = "0.7.0"
