[package]
name = "rolling"
version = "0.1.0"
authors = ["Bastien Sevajol <sevajol.bastien@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2"
crossbeam = "0.7.1"
num_cpus = "1.10.0"
rand = "0.6.5"
